# Generated by Django 3.2.5 on 2021-07-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='mixin',
            field=models.CharField(default='x', max_length=100),
            preserve_default=False,
        ),
    ]
